### PR TITLE
chore: rename project files

### PR DESCRIPTION
**Pull request by fzipi**
## what

- rename project directory
- update logos to reflect new `CRS` name

### CODE REVIEW

**Comment by fzipi** [comment]
@dune73 Can you approve this update?

**Review by kingthorin — APPROVED** [review]
Seems fine to me. I'll defer to @dune73 though

**Review by dune73 — APPROVED** [review]

**Comment by dune73** [comment]
Thanks @fzipi 

For the record: We are slowly moving from "ModSecurity Core Rule Set" to "CRS". Namely to reflect the fact that beyond OWASP ModSecurity, there is also OWASP Coraza and commercial engines running CRS.

The downside of CRS is that it does not have any connection with WAF nor Security, but lengthy discussions to come up with a better alternative lead to stalemate, so we're on OWASP CRS now.

**Comment by kingthorin** [comment]
Thank you both!

**Pull request merged**
