### PR TITLE
provide credit for threat dragon artwork

### PR DESCRIPTION
**Pull request by jgadsden**
This pull request gives credit for the Threat Dragon artwork to the original artist, who has given written permission for us to use this artwork if it is not-for-profit.

:information_source: Please make sure you have read and are [adhering to the rules](https://github.com/OWASP/owasp-swag#rules) ([:uk:](https://github.com/OWASP/owasp-swag#rules)/[:jp:](https://github.com/OWASP/owasp-swag/blob/master/README_JP.md#%E3%83%AB%E3%83%BC%E3%83%AB)) for additions to this repository!

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by jgadsden** [comment]
@bkimminich or @kingthorin did you want to merge this PR in? Successfully reviewed, thanks

**Comment by kingthorin** [comment]
I don’t have perms to merge in this repo 😞

**Comment by psiinon** [comment]
@kingthorin I think it would be good it you could.
You'll need to be added to the owasp-swag-admin team - I'm in there .. but I cant add you :/
Not sure who can tbh...

**Comment by jgadsden** [comment]
this may be something that @hblankenship or @alyssa-hardin can help with?

**Comment by alyssa-hardin** [comment]
Hello Jon,

Is there something I can help you with? If so, please let me know and I
will do my best to assist you. Harold is on vacation. Thank you.

Kind Regards,
Alyssa Hardin

**Comment by jgadsden** [comment]
Hello @alyssa-hardin , could you add @kingthorin to the owasp-swag-admin team please? Many thanks!

**Comment by alyssa-hardin** [comment]
I saw that @kingthorin was already a collaborator in a “maintain” role. I switched Rick over to admin and he should have admin privileges now. If not, please let me know. Thank you.

Thanks,
Alyssa

**Comment by kingthorin** [comment]
Thanks, being added as a maintainer was just a temporary step until some (hopefully you or Harold could add me to the right group).

**Comment by alyssa-hardin** [comment]
Do you have the admin privileges now? I switched you to admin group.  On Aug 3, 2023, at 11:05 PM, Rick M ***@***.***> wrote:﻿
Thanks, being added as a maintainer was just a temporary step until some (hopefully you or Harold could add me to the right group).

**Comment by kingthorin** [comment]
Yes I do seem to. Sorry if my reply didn't make sense, your previous message was unclear to me if you simply changed my permissions or actually added me to the group. Seems good from my end. Have a great weekend!

**Comment by alyssa-hardin** [comment]
No problem at all! I am glad we got that squared away. Sorry for any confusion. On Aug 4, 2023, at 11:24 AM, Rick M ***@***.***> wrote:﻿
Yes I do seem to. Sorry if my reply didn't make sense, your previous message was unclear to me if you simply changed my permissions or actually added me to the group. Seems good from my end. Have a great weekend!

**Pull request merged**
