### PR TITLE
Add Kyiv chapter logos.

### PR DESCRIPTION
**Pull request by sapran**

### CODE REVIEW

**Comment by psiinon** [comment]
Maybe we should have all directory names in lowercase?
(Standards are 'evolving' ;)

**Comment by bkimminich** [comment]
Shouldn't we use international city/country names? Otherwise it might get very confusing at some point. Also, @sapran, please remove the `.jpg` versions as they are unlikely to ever be useful for printing on stickers, shirts etc.

**Comment by bkimminich** [comment]
@sapran, are you planning to send a new PR? I checked the OWASP Wiki and probably the chapter names should equal what is found there, not necessarily the the internationalized name. So in your case this might be best: `ukraine/kyiv` and in there only the PNG/AI/EPS files.

**Comment by takaharuogasa** [comment]
Looking forward to seeing your logo on this repo @sapran :)

**Pull request closed without merging**
